PRODUCT_PROPERTY_OVERRIDES +=  \
    af.fast_track_multiplier=1 \
    audio.deep_buffer.media=true \
    audio.offload.min.duration.secs=30 \
    audio.offload.video=true \
    dalvik.vm.foreground-heap-growth-multiplier=2.0 \
    dalvik.vm.heapgrowthlimit=128m \
    dalvik.vm.heapmaxfree=8m \
    dalvik.vm.heapminfree=2m \
    dalvik.vm.heapsize=512m \
    dalvik.vm.heapstartsize=8m \
    dalvik.vm.heaptargetutilization=0.75 \
    drm.service.enabled=true \
    keyguard.no_require_sim=true \
    persist.cne.feature=0 \
    persist.data.dpm.enable=true \
    persist.data.dropssdp=false \
    persist.data.ibfc.enable=true \
    persist.data.mode=concurrent \
    persist.data.netmgrd.qos.enable=false \
    persist.hwc.enable_vds=1 \
    persist.radio.apm_sim_not_pwdn=1 \
    persist.radio.atfwd.start=true \
    persist.radio.embms.support=false \
    persist.radio.latest-modeltype=2,2 \
    persist.radio.multisim.config=dsds \
    persist.radio.multisim.stackid=0,1 \
    persist.radio.schd.cache=3500 \
    persist.radio.sib16_support=1 \
    persist.radio.silent-reset=27 \
    persist.radio.ss.voiceclass_1=false \
    persist.vendor.radio.custom_ecc=1 \
    persist.vendor.radio.rat_on=combine \
    persist.vendor.radio.sib16_support=1 \
    persist.vendor.audio.fluence.speaker=true \
    persist.vendor.audio.fluence.voicecall=true \
    persist.vendor.audio.fluence.voicerec=false \
    persist.vendor.audio.speaker.prot.enable=false \
    persist.vendor.bt.enable.splita2dp=false \
    persist.vendor.qcomsysd.enabled=0 \
    pm.dexopt.shared=quicken \
    qemu.hw.mainkeys=0 \
    ro.build.shutdown_timeout=0 \
    ro.control_privapp_permissions=log \
    ro.error.receiver.default=com.samsung.receiver.error \
    ro.frp.pst=/dev/block/persistent \
    ro.hardware.gatekeeper=mdfpp \
    ro.hardware.keystore=mdfpp \
    ro.hardware.nfc_nci=nqx.default \
    ro.lmk.critical_upgrade=true \
    ro.lmk.upgrade_pressure=40 \
    ro.opa.eligible_device=true \
    ro.security.icd.flagmode=multi \
    ro.security.keystore.keytype=gak \
    ro.security.vpnpp.release=1.0 \
    ro.security.vpnpp.ver=2.1 \
    ro.vendor.audio.sdk.fluencetype=none \
    ro.vendor.audio.sdk.ssr=false \
    ro.vendor.extension_library=libqti-perfd-client.so \
    ro.vendor.qti.am.reschedule_service=true \
    security.ASKS.policy_version=000000 \
    sys.vendor.shutdown.waittime=500 \
    vendor.audio.dolby.ds2.enabled=false \
    vendor.audio.dolby.ds2.hardbypass=false \
    vendor.audio.flac.sw.decoder.24bit=true \
    vendor.audio.hw.aac.encoder=true \
    vendor.audio.offload.buffer.size.kb=64 \
    vendor.audio.offload.gapless.enabled=true \
    vendor.audio.offload.multiaac.enable=true \
    vendor.audio.offload.multiple.enabled=false \
    vendor.audio.offload.passthrough=false \
    vendor.audio.offload.track.enable=true \
    vendor.audio.parser.ip.buffer.size=262144 \
    vendor.audio.playback.mch.downsample=true \
    vendor.audio.pp.asphere.enabled=false \
    vendor.audio.safx.pbe.enabled=true \
    vendor.audio.tunnel.encode=false \
    vendor.audio.use.sw.alac.decoder=true \
    vendor.audio.use.sw.ape.decoder=true \
    vendor.audio_hal.period_size=192 \
    vendor.display.enable_default_color_mode=1 \
    vendor.sec.rild.libpath2=/vendor/lib/libsec-ril-dsds.so \
    vendor.sec.rild.libpath=/vendor/lib/libsec-ril.so \
    vendor.vidc.disable.split.mode=1 \
    vendor.voice.conc.fallbackpath=deep-buffer \
    vendor.voice.path.for.pcm.voip=true \
    vendor.voice.playback.conc.disabled=true \
    vendor.voice.record.conc.disabled=false \
    vendor.voice.voip.conc.disabled=true \
    persist.service.adb.enable=1 \
    persist.service.debuggable=1 \
    persist.sys.usb.config=mtp,adb \
    ro.sf.lcd_density=320 \
    ro.telephony.default_network=9 \
    ro.telephony.call_ring.multiple=false \
    ro.telephony.default_cdma_sub=0 \
    ro.carrier=unknown \
    wifi.interface=wlan0 \
    ro.config.bservice_enable=true \
    ro.multisim.simslotcount=2 \
    ro.vendor.multisim.simslotcount=2 \
    vendor.perf.iop_v3.enable=true  \
    persist.vendor.radio.apm_sim_not_pwdn=1 \
    persist.vendor.radio.atfwd.start=true \
    ro.use_data_netmgrd=true \
    rild.libpath=/vendor/lib/libsec-ril.so \
    rild.libpath2=/vendor/lib/libsec-ril-dsds.so \
    ro.sys.sdcardfs=true \
    vendor.gralloc.disable_ubwc=1 \
    debug.gralloc.gfx_ubwc_disable=1 \
	#ril.subscription.types=NV,RUIM \
	#DEVICE_PROVISIONED=1 \
    #ro.telephony.ril_class=SamsungQcomRIL





#rild.libpath=/system/vendor/lib/libril-qc-qmi-1.so \
#    vendor.rild.libpath=/system/vendor/lib/libril-qc-qmi-1.so \
    



#    rild.libargs=-d /dev/umts_ipc0 \
#    rild.libpath=/vendor/lib/libsec-ril.so \
#    rild.libpath2=/vendor/lib/libsec-ril-dsds.so \

#    rild.libpath=/system/vendor/lib/libril-qc-qmi-1.so \
#    ro.sf.init.lcd_density=320 \
#   ro.config.low_ram=true \ \
#    ro.com.google.clientidbase=android-samsung-ss \
#    ro.com.google.gmsversion=8.1_201812.go \
#    ro.config.alarm_alert=Morning_Glory.ogg \
#    ro.config.notification_sound=Skyline.ogg \
#    ro.config.notification_sound_2=S_Charming_Bell.ogg \
#   ro.config.ringtone=Over_the_Horizon.ogg \
#    ro.config.ringtone_2=Basic_Bell.ogg \
#    pm.dexopt.downgrade_after_inactive_days=10 \
#    ro.setupwizard.mode=OPTIONAL \
#    ro.setupwizard.wifi_on_exit=false \
